### ISSUE TITLE
How to get *another* ActorRef from an ActorSystem

### ISSUE THREAD

**Issue by igalic** [riker-rs/riker#133]
i'm trying to store the (reference? to) the `ActorSystem` in my server's state management facility, to allow the various request handling threads of the server to have access to *all* the `Actor`s of the `ActorSystem` in it.

But i don't understand how to get an `ActorRef` from the `ActorSystem` *again* after the `Actor` has already been started in `main()`.
request handlers are short-lived, and it doesn't make sense for them to start `Actor`s, let alone have all the information passed to them that would allow them to start those `Actor`s.

From what I gather, the only way to do that, is to use [Selection](https://riker.rs/selection/)

**Comment by drogus** [comment]
I'm not sure how to do it in Riker, but maybe you could potentially use `Arc<Mutex<ActorSystem>>` and pass it around like that?

**Comment by igalic** [comment]
that's basically what I'm already doing (well, without the `Mutex` yet…)

but then how do i access an actor that's already started?

**Comment by hardliner66** [comment]
I think in actor systems it's normal to hold on to references once you create them and pass them to the other actors who need them.

**Comment by igalic** [comment]
yes, I'd just like to not pass around 5 references, when i'm also holding the ActorSystem

**Comment by hardliner66** [comment]
IMO passing around should be preferred, because then all your dependencies are more explicit. But if you don't want to do that, actor selection is probably the way to go.

**Comment by igalic** [comment]
aye. and that is the route we've taken, so we're on the correct (enough) path
