### ISSUE TITLE
Persist actors using redis / postgres / etc

### ISSUE THREAD

**Issue by kunjee17** [riker-rs/riker#138]
While going through documentation I did found out key to persist actors but was unable to find out anything other than that. No documents or event tried to find code but was unable to do so. Is that feature already implemented or yet to implement?

**Comment by hardliner66** [comment]
@kunjee17 Persistance is currently not implemented. See: https://github.com/riker-rs/riker/pull/118

**Comment by kunjee17** [comment]
Thanks closing the issue for now.
