### ISSUE TITLE
`Running Futures` example is invalid

### ISSUE THREAD

**Issue by berkus** [riker-rs/riker#169]
As displayed in the example code:
```
let handle = system.run(async move {
    "someval".to_string()
});

assert_eq!(block_on(handle), "someval".to_string());
```

This will not even build because run() returns Result<RemoteHandle...> and block_on() expects a non-Result argument.

**Comment by berkus** [comment]
If you try to unwrap() and run block_on(handle.unwrap()) then riker will crash with:

thread 'pool-thread-#0' panicked at 'cannot execute LocalPool executor from within another executor: EnterError', 
stack backtrace:
thread 'pool-thread-#4' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'

**Comment by knepe** [comment]
Any news on this? 
I'm having the exact same issue

**Comment by hardliner66** [comment]
@knepe the riker project is abandoned. The original maintainer vanished without saying anything. It's probably better to migrate towards a different actor framework.

For the problem itself:
`block_on` must be called from a tokio context. That means, you need to run your app as a tokio app and run `block_on` from there.

**Comment by knepe** [comment]
Ah damn :( Thanks!

**Comment by berkus** [comment]
@knepe https://github.com/slawlor/ractor perhaps :)
