### ISSUE TITLE
slack channel?

### ISSUE THREAD

**Issue by thedavidmeister** [riker-rs/riker#20]
could be cool to have a channel to discuss riker

is it possible to create a new channel under the main rust slack?

**Comment by kitsuneninetails** [comment]
There is a Gitter channel at: https://gitter.im/riker-rs/Lobby if that helps.  We should definitely get a Slack set up as well.  Thanks!

**Comment by thedavidmeister** [comment]
it does help, we should get the gitter link in the readme somewhere prominent :D @kitsuneninetails
