### ISSUE TITLE
Perhaps error in example

### ISSUE THREAD

**Issue by vchekan** [riker-rs/riker#49]
https://github.com/riker-rs/riker/blob/7c06e29bb0f717df9ab969501e905c6b4d019716/src/actor/props.rs#L33

Shouldn't it be `Box::new(User {})`?
And the same problem in README.md

**Comment by leenozara** [comment]
Hi @vchekan thanks for checking. In this case it's not an error. `User` is a unit struct defined using `struct User;` without any fields and an instance can be created using just `let x = User`.
