### ISSUE TITLE
Typos in tutorial

### ISSUE THREAD

**Issue by robwebbjr** [riker-rs/riker#72]
Hi.
Thank you for making Riker!

In the "Message Types" section of the tutorial the code for implementing Receiver<Sub> and Receiver<Print> both have _msg: Add ...

The example ran correctly after changing _msg: to Sub and Print, respectively.

I didn't try running it as is...

Thanks.

P.S. I am going to try to use Seed (a WASM web-framework) with Riker, just to experiment and learn. Is there anything you think I should know about using Riker with WASM?

Noob to webdev, Rust, actors, distributed computing, etc. (pretty much a noob to all this tech with Rust being my first language for anything more than dabbling (dabbled with Haskell and Python each for a bit...)).
email is rob.webb.jr@gmail.com

**Comment by leenozara** [comment]
Hi @robwebbjr thanks for spotting those typos! It's been fixed on the site now.

I'm not too familiar myself with WASM but there are a few people in the Riker community that are voicing interesting in combining Riker with WASM. You are always welcome to check in the group chat at https://gitter.im/riker-rs/Lobby. There might be other folks trying to do something similar. I can always assist with general distributed computing and actor questions, as well as Riker specific ones.

Really looking forward to seeing what you build.
