### ISSUE TITLE
Use of std::sync::Mutex in run_mailbox

### ISSUE THREAD

**Issue by mrjoe7** [riker-rs/riker#73]
I was looking into mailbox code and nocited that `std::sync::Mutex` is used in [`run_mailbox`](https://github.com/riker-rs/riker/blob/master/src/kernel/mailbox.rs#L196) which is called from `async` block at [`kernel.rs:73`](https://github.com/riker-rs/riker/blob/master/src/kernel/kernel.rs#L73).

`std::sync::Mutex` should not be used in an asynchronous environment, because a mutex acquisition can block an entire reactor. Instead a [`futures::lock::Mutex`](https://docs.rs/futures-preview/0.3.0-alpha.18/futures/lock/struct.Mutex.html) should be used there to make sure the code won't block an executor.

**Comment by leenozara** [comment]
Nice spot! Did you want to try to fork, change to `futures::lock::Mutex` yourself and create a PR?

**Comment by mrjoe7** [comment]
I might try to update the code when I have some free time.

**Comment by mrjoe7** [comment]
I spent some looking into the code and did not find any `.await` boundary crossing mutex locks.
Now I believe there are no deadlocks possible in the current code.
