### ISSUE TITLE
Actor::post_start is never called

### ISSUE THREAD

**Issue by mrjoe7** [riker-rs/riker#75]
Code in https://github.com/riker-rs/riker/blob/master/src/kernel/mailbox.rs#L307-L311 is commented out, so Actor::post_start is never called.

**Comment by tupshin** [comment]
This should either be removed from the api/documentation or get fixed. Is there a reason that code was disabled?

**Comment by hardliner66** [comment]
It seems the post_start was only called if persistence is enabled, but because the persistence code is not functional and commented out, this was commented out too.

I created a pull request because I think this can safely be re-enabled.
