### ISSUE TITLE
Update to stable dependencies

### ISSUE THREAD

**Issue by ancwrd1** [riker-rs/riker#80]
The current version still has alpha dependencies in the manifest file.
Would be great to update them to the released ones.

**Comment by hardliner66** [comment]
futures can be moved from alpha to stable, but pin-utils currently only exists as an alpha version ([relevant pull request](https://github.com/rust-lang-nursery/pin-utils/pull/26)).

**Comment by hardliner66** [comment]
It seems pin-utils is out of alpha too. https://crates.io/crates/pin-utils

**Comment by leenozara** [comment]
We’ll get everything updated to latest Rust + futures + stable/nightly once PR #84 is completed and merged.
